### ISSUE TITLE
found staticlib `curl` instead of rlib or dylib

### ISSUE THREAD

**Issue by Lucas-C** [tokio-rs/tokio-curl#14]
Hello.

I'm a newbie with Rust, but I just wanted to try your main example: https://docs.rs/tokio-curl/0.1.9/tokio_curl/

I put the following in my `Cargo.toml`:
```
[package]
name = "example"
version = "0.0.1"
authors = [ "Lucas Cimon" ]

[dependencies]
tokio-curl = "0.1.9"

[[bin]]
name = "example"
path = "example.rs"
```

But I get the following error:
```
# cargo --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
# rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
# cargo run
...
   Compiling example v0.0.1 (file:///root)
error[E0462]: found staticlib `curl` instead of rlib or dylib
 --> example.rs:1:1
  |
1 | extern crate curl;
  | ^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using --crate-type lib
  = note: crate `curl` path #1: /root/target/debug/build/curl-sys-51dabcf5583e5190/out/lib/libcurl.a

error: aborting due to previous error

error: Could not compile `example`.

To learn more, run the command again with --verbose.
```

Could you help me with this please ?
I tried the `curl` crate 1st example and it worked fine : https://github.com/alexcrichton/curl-rust

**Comment by alexcrichton** [comment]
Oh this was actually a [bug](https://github.com/alexcrichton/curl-rust/commit/7b28e1ab720463ffef4f63d0e7ddef7d70e0aeb0) in the curl build script sort. The real error here is that if you want to write `extern crate curl` you'll *also* need to depend on curl, e.g. `curl = "0.4"`

**Comment by Lucas-C** [comment]
Ok, thank you very much !
That solved my problem :)
