### ISSUE TITLE
panic related to timeout - repeat of #2

### ISSUE THREAD

**Issue by donhcd** [tokio-rs/tokio-curl#4]
I'm getting an intermittent panic here: https://github.com/tokio-rs/tokio-curl/blob/a5788cd2079b873ce0938fca59f5e1affa9208b6/src/unix.rs#L204

I was getting the panic mentioned in #2 when I was using the crates.io dependency, so I switched to master's sha but it seems like I'm still hitting the same (or similar) case.

I'll try enabling logging and see if I can repro, but I wanted to give a heads up about this

**Comment by alexcrichton** [comment]
Thanks for the report!

Can you get a log of a failure with `RUST_LOG=debug`?

**Comment by FoundOne** [comment]
I have the same problem.
RUST_LOG=debug gives nothing more than:
 ```
.thread 'main' panicked at 'timeout done immediately?', /home/dwolf/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-curl-0.1.0/src/unix.rs:193
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
RUST_BACKTRACE=1 gives me this:
https://gist.github.com/FoundOne/9b50c819fc6a6c23523142d73dbdcc86#file-tokio_curl_backtrace-txt

**Comment by alexcrichton** [comment]
@FoundOne oh you may have to set up the `env_logger` crate in your project with `env_logger::init`, then perhaps the logs will come out?

I'd also recommend using the git master version of this crate which has the fix for #2. I'll be sure to make a release after this is fixed.

**Comment by FoundOne** [comment]
With the git master version it just hangs out and the debug output looks like:
`     Running `target/debug/curl_check`
DEBUG:tokio_core::reactor: adding a new I/O source
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 21295 }
DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 794523, tv_nsec: 185292589 }
DEBUG:tokio_curl::imp: -------------------------- driver poll start
DEBUG:tokio_curl::imp: executing a new request
DEBUG:tokio_curl::imp: scheduling a new timeout in Duration { secs: 0, nanos: 0 }
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 0
DEBUG:tokio_curl::imp: 	event cancel 0
DEBUG:tokio_curl::imp: timeout fired
DEBUG:tokio_curl::imp: scheduling a new timeout in Duration { secs: 0, nanos: 0 }
DEBUG:tokio_core::reactor: loop process - 2 events, Duration { secs: 0, nanos: 262366 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5198 }
DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 794523, tv_nsec: 185579441 }
DEBUG:tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 1052 }`

**Comment by donhcd** [comment]
@FoundOne what do you mean by "hangs out"? Is your program hanging?

**Comment by FoundOne** [comment]
@donhcd Yes. It just stays and does nothing.

**Comment by alexcrichton** [comment]
@donhcd hm is there perhaps a small gist of what's going on to reproduce this I could try out locally? Also, what platform are you on?


@FoundOne could you gist the program you're compiling there? Also, what platform are you on as well?

**Comment by FoundOne** [comment]
I'm on Arch Linux x86_64 hybrid. Here is the gist of the program: 
https://gist.github.com/FoundOne/470766d266eed5ead5908e6cacb7991a#file-main-rs

**Comment by alexcrichton** [comment]
hm, @FoundOne could you try bumping the log level up to `RUST_LOG=trace` and see what it prints when it hangs?

**Comment by FoundOne** [comment]
That's the output from RUST_LOG=trace RUST_BACKTRACE=1
https://gist.github.com/FoundOne/26579a679bc20e87bcbf17d605bab32e#file-debug_trace-txt

**Comment by donhcd** [comment]
@alexcrichton I have a bunch of code surrounding where I use `tokio-curl`, but the [gist of it](https://github.com/donhcd/tokio_test/blob/83043d0049c5eb51c5061db4b4c428fe0351ad01/src/main.rs) is pretty much identical to [your test](https://github.com/tokio-rs/tokio-curl/blob/master/tests/smoke.rs#L15). I think the only difference is that it runs on another thread. 

My coworker got the panic on the latest OSX (10.12 sierra)

**Comment by alexcrichton** [comment]
Hm let's perhaps try another angle, what version of libcurl is being used? Is the system library coming into play, and in case what version? If not, is the bundled libcurl getting compiled and being used?

**Comment by FoundOne** [comment]
The curl library is libcurl.so.4.4.0 (pacman says curl 7.50.3-1 about curl) and the crate is v0.3.7. I tried just the curl crate yesterday and it worked. Here is the list of all dependancies compiled.
 ```
Compiling winapi v0.2.8
   Compiling log v0.3.6
   Compiling regex-syntax v0.3.5
   Compiling winapi-build v0.1.1
   Compiling void v1.0.2
   Compiling slab v0.3.0
   Compiling lazycell v0.4.0
   Compiling scoped-tls v0.1.0
   Compiling utf8-ranges v0.1.3
   Compiling pkg-config v0.3.8
   Compiling bitflags v0.4.0
   Compiling libc v0.2.16
   Compiling semver v0.1.20
   Compiling gcc v0.3.35
   Compiling kernel32-sys v0.2.2
   Compiling futures v0.1.2
   Compiling cfg-if v0.1.0
   Compiling openssl-sys v0.7.17
   Compiling libz-sys v1.0.6
   Compiling curl-sys v0.2.3
   Compiling rustc_version v0.1.7
   Compiling memchr v0.1.11
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling aho-corasick v0.5.3
   Compiling nix v0.6.0
   Compiling net2 v0.2.26
   Compiling curl v0.3.7
   Compiling regex v0.1.77
   Compiling mio v0.6.0
   Compiling tokio-core v0.1.0
   Compiling tokio-curl v0.1.0 (https://github.com/tokio-rs/tokio-curl.git#a5788cd2)
   Compiling env_logger v0.3.5
```

**Comment by alexcrichton** [comment]
gah I have no idea why I can't reproduce this :(

@FoundOne did you ever get `env_logger` to work with `RUST_LOG=trace` output?

**Comment by FoundOne** [comment]
@alexcrichton [this](https://gist.github.com/FoundOne/26579a679bc20e87bcbf17d605bab32e#file-debug_trace-txt) is the only input from RUST_LOG=trace and it gives "TRACE:" mesages.
I made some tests. It's doing 0 seconds timeout for some reason. I'm still seraching for the problem. It's strange that the event loop continues.

**Comment by alexcrichton** [comment]
The 0 second timeouts are expected as they're curl's way of saying "inform me of a timeout ASAP", so those are at least expected.

Out of curiosity, does [this patch](https://gist.github.com/5e4857f551037361da959c50f8d571f0) help at all?

**Comment by FoundOne** [comment]
It works. Thank you!

**Comment by donhcd** [comment]
@alexcrichton seems like I'm encountering the same bug on 0.1.2... I didn't have the tokio_curl=trace set at the time though. I'd guess that perhaps turning on the logging reduces the chances of the panic occurring?

[backtrace](http://sprunge.us/aRgT)

I'm on osx 10.11.5, with the `curl` crate at 0.3.7 and the `curl-sys` crate at 0.2.3. I'm not sure whether the bundled version of libcurl is being used, but `curl-config --version` gives me
`libcurl 7.43.0`

in the meantime I've switched tokio-curl tracing back on but I'm not sure if I'll be able to repro with it on

**Comment by alexcrichton** [comment]
@donhcd if you apply [this patch](https://gist.github.com/alexcrichton/aa4de89a58bfb86c35d04f81b0cbc6bb) does it work for you? Note that that may have a chance to busy wait, so you may want to also check to ensure the CPU usage isn't too high.

**Comment by donhcd** [comment]
@alexcrichton thanks! I'll try applying it and removing logging and seeing if there are issues. unfortunately I seem to be hitting that case quite rarely, so I can only confidently say if that patch *doesn't* work

**Comment by alexcrichton** [comment]
Ok, I've pushed that to master and I'll try to deal with #5 before publishing.
