### ISSUE TITLE
[Bug]: tokio-curl tries to access dropped socket

### ISSUE THREAD

**Issue by FoundOne** [tokio-rs/tokio-curl#5]
What happens: It happens randomly when downloading many pages simultaneously. Sometimes tokio-curl drops a socket from the slab and then tries to reuse it.
RUST_BACKTRACE=1 RUST_LOG=trace output example: [here](https://gist.github.com/FoundOne/8d75b7ea9f0904e4f2ee2f55b7db9734#file-out_example-txt)
Way to reproduce: [example](https://gist.github.com/FoundOne/c394bdab1708455cbcdb00b7f520ed50#file-main-rs)
OS: Arch Linux x86_64 hybrid

**Comment by FoundOne** [comment]
I've made a [fix](https://gist.github.com/FoundOne/3fc483cb5317c1d5ba5f38d3e42886ba#file-fix_socket-patch) but it needs some testing.

**Comment by NeoLegends** [comment]
Got the same issues when I'm running tests that do network requests on travis.

**Comment by FoundOne** [comment]
Oops. I placed the check in the wrong place. I was quite sleepy back then. I'm sorry about that. Now it's corrected.

**Comment by alexcrichton** [comment]
Thanks for the report! I'll publish a new version with the fix
